#!/bin/sh

# Copyright 2015, Timothy Redaelli <tredaelli@archlinux.info>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License at <http://www.gnu.org/licenses/> for
# more details.

set -e

# Gathering informations about actual environment.
if command -v wget >/dev/null 2>&1; then
	_download() { wget -U vps2arch -O- "$@" ; }
elif command -v curl >/dev/null 2>&1; then
	_download() { curl -A vps2arch -fL "$@" ; }
else
	echo "This script needs curl or wget" >&2
	exit 2
fi

get_mirrors() {
	echo "https://fastly.mirror.pkgbuild.com/ https://geo.mirror.pkgbuild.com/ https://ftpmirror.infania.net/mirror/archlinux/ http://mirror.rackspace.com/archlinux/ https://mirror.rackspace.com/archlinux/"
}

cpu_type=$(uname -m)

is_openvz() { [ -d /proc/vz -a ! -d /proc/bc ]; }
is_lxc() { grep -aqw container=lxc /proc/1/environ ; }

download() {
	local path="$1" x=
	shift
	for x in $mirrors; do
		_download "$x$path" && return 0
	done
	return 1
}

download_and_extract_bootstrap() {
	local sha256 filename
	download iso/latest/sha256sums.txt | egrep "[[:digit:]]-$cpu_type.tar.zst" > "sha256sums.txt"
	read -r sha256 filename < "sha256sums.txt"
	download "iso/latest/$filename" > "$filename"
	sha256sum -c sha256sums.txt || exit 1
	zstdcat "$filename" | tar -xpf -
	rm -f "$filename"

	if grep -E '^nameserver\s+127\.' /etc/resolv.conf > /dev/null; then
		echo "nameserver 8.8.8.8" > "/root.$cpu_type/etc/resolv.conf"
	else
		cp -L /etc/resolv.conf "/root.$cpu_type/etc"
	fi

	# Mount options taked from arch-chroot script
	mount -t proc proc -o nosuid,noexec,nodev "/root.$cpu_type/proc"
	mount -t sysfs sys -o nosuid,noexec,nodev,ro "/root.$cpu_type/sys"
	mount -t devtmpfs -o mode=0755,nosuid udev "/root.$cpu_type/dev"
	mkdir -p "/root.$cpu_type/dev/pts" "/root.$cpu_type/dev/shm"
	mount -t devpts -o mode=0620,gid=5,nosuid,noexec devpts "/root.$cpu_type/dev/pts"
	mount -t tmpfs -o mode=1777,nosuid,nodev shm "/root.$cpu_type/dev/shm"
	mount -t tmpfs -o nosuid,nodev,mode=0755 run "/root.$cpu_type/run"
	mount -t tmpfs -o mode=1777,strictatime,nodev,nosuid tmp "/root.$cpu_type/tmp"
	# FIXME support multiple partitions
	mount --bind / "/root.$cpu_type/mnt"
	findmnt /boot >/dev/null && mount --bind /boot "/root.$cpu_type/mnt/boot"
	findmnt /boot/efi >/dev/null && mount --bind /boot/efi "/root.$cpu_type/mnt/boot/efi"
	# Workaround for Debian
	mkdir -p "/root.$cpu_type/run/shm"
	# Workaround for OpenVZ
	rm -f "/root.$cpu_type/etc/mtab"
	cp -L /etc/mtab "/root.$cpu_type/etc/mtab"
}

chroot_exec() {
	chroot "/root.$cpu_type" /bin/bash -c "$*"
}

configure_chroot() {
	local m
	for m in $mirrors; do
		echo 'Server = '"$m"'/$repo/os/$arch'
	done >> "/root.$cpu_type/etc/pacman.d/mirrorlist"
	# Install and initialize haveged if needed
	if ! is_openvz && ! pidof haveged >/dev/null; then
		# Disable signature check, install and launch haveged and re-enable signature checks.
		sed -i.bak "s/^[[:space:]]*SigLevel[[:space:]]*=.*$/SigLevel = Never/" "/root.$cpu_type/etc/pacman.conf"
		chroot_exec 'pacman --needed --noconfirm -Sy haveged && haveged'
		mv "/root.$cpu_type/etc/pacman.conf.bak" "/root.$cpu_type/etc/pacman.conf"
	fi
	chroot_exec 'pacman-key --init && pacman-key --populate archlinux'
	chroot_exec 'pacman --needed --noconfirm -Sy archlinux-keyring'
	# Generate fstab
	chroot_exec 'genfstab /mnt >> /etc/fstab'

	# Configure locale
	sed -i "s/^#\($user_locale\)/\1/" "/root.$cpu_type/etc/locale.gen"
	chroot_exec 'locale-gen'
	echo "LANG=$user_locale" > "/root.$cpu_type/etc/locale.conf"

	if is_openvz && [ "$kernelver" '<' '2.6.32-042stab111.1' ]; then
		# Use my repository for OpenVZ-patched systemd
		sed -i 's;^#\[testing\]$;[tredaelli-systemd]\nServer = http://pkgbuild.com/~tredaelli/repo/systemd/$arch\n\n&;' "/root.$cpu_type/etc/pacman.conf"
	fi
}

save_root_pass() {
	grep '^root:' /etc/shadow > "/root.$cpu_type/root.passwd"
	chmod 0600 "/root.$cpu_type/root.passwd"
}

delete_all() {
	# Remove immutable flag from any files / directories
	if command -v chattr >/dev/null 2>&1; then
		find / -type f \( ! -path '/dev/*' -and ! -path '/proc/*' -and ! -path '/sys/*' -and ! -path '/selinux/*' -and ! -path "/root.$cpu_type/*" \) \
			-exec chattr -i {} + 2>/dev/null || true
	fi
	# Delete *all* files from /
	find / \( ! -path '/dev/*' -and ! -path '/proc/*' -and ! -path '/sys/*' -and ! -path '/selinux/*' -and ! -path "/root.$cpu_type/*" \) -delete 2>/dev/null || true
}

install_packages() {
	local packages="base linux lvm2 openssh vim bash-completion"
	[ "$bootloader" != "none" ] && packages="$packages $bootloader"
	# XXX Install gptdisk for syslinux. To be removed then FS#45029 will be closed
	[ "$bootloader" = "syslinux" ] && packages="$packages gptfdisk"
	[ -f /sys/firmware/efi/fw_platform_size ] && packages="$packages efibootmgr"
	[ "$network" = "netctl" ] && packages="$packages netctl"
	while read -r _ mountpoint filesystem _; do
		[ "$mountpoint" = "/" -a "$filesystem" = "xfs" ] && packages="$packages xfsprogs"
	done < /proc/mounts
	# Black magic!
	"/root.$cpu_type/usr/lib"/ld-*.so.2 --library-path "/root.$cpu_type/usr/lib" \
		"/root.$cpu_type/usr/bin/chroot" "/root.$cpu_type" /usr/bin/pacstrap -M /mnt $packages
	cp -L "/root.$cpu_type/etc/resolv.conf" /etc

	# Copy skel files to /root
	cp -a "/root.$cpu_type/etc/skel/." "/root.$cpu_type/mnt/root/"
}

restore_root_pass() {
	# If the root password is not set, use vps2arch
	if egrep -q '^root:[^$]' "/root.$cpu_type/root.passwd"; then
		echo "root:vps2arch" | chpasswd
	else
		sed -i '/^root:/d' /etc/shadow
		cat "/root.$cpu_type/root.passwd" >> /etc/shadow
	fi
}

cleanup() {
	mv "/root.$cpu_type/etc/fstab" "/etc/fstab"
	awk "/\/root.$cpu_type/ {print \$2}" /proc/mounts | sort -r | xargs umount -nl || true
	rm -rf "/root.$cpu_type/"
}

configure_bootloader() {
	local root_dev=$(findmnt -no SOURCE /) root_devs= tmp= needs_lvm2=0 uefi=0
	case $root_dev in
	/dev/mapper/*) needs_lvm2=1 ;;
	esac
	if [ -f /sys/firmware/efi/fw_platform_size ]; then
		uefi=$(cat /sys/firmware/efi/fw_platform_size)
	fi

	if [ $needs_lvm2 -eq 1 ]; then
		# Some distro doesn't use lvmetad by default
		sed -i.bak 's/use_lvmetad = 1/use_lvmetad = 0/g' /etc/lvm/lvm.conf
	fi

	if [ "$bootloader" = "grub" ]; then
		# If you are still using eth* as interface name, disable "strange" ifnames
		grep -q '^[[:space:]]*eth' /proc/net/dev && \
			sed -i.bak 's/GRUB_CMDLINE_LINUX_DEFAULT="/&net.ifnames=0 /' /etc/default/grub

		# Disable "graphic" terminal output
		sed -i.bak 's/^#GRUB_TERMINAL_OUTPUT=console/GRUB_TERMINAL_OUTPUT=console/' /etc/default/grub

		if [ $needs_lvm2 -eq 1 ]; then
			local vg
			vg=$(lvs --noheadings $root_dev | awk '{print $2}')
			root_dev=$(pvs --noheadings | awk -v vg="$vg" '($2 == vg) { print $1 }')
		fi
		for root_dev in $root_dev; do
			tmp=$(lsblk -npsro TYPE,NAME "$root_dev" | awk '($1 == "disk") { print $2}')
			case " $root_devs " in
			*" $tmp "*) 	;;
			*)		root_devs="${root_devs:+$root_devs }$tmp"	;;
			esac
		done
		case $uefi in
		0)
			for root_dev in $root_devs; do
				grub-install --target=i386-pc --recheck --force "$root_dev"
			done
			;;
		64)
			grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=GRUB
			;;
		esac
		grub-mkconfig > /boot/grub/grub.cfg
	elif [ "$bootloader" = "syslinux" ]; then
		# If you are still using eth* as interface name, disable "strange" ifnames
		grep -q '^[[:space:]]*eth' /proc/net/dev && tmp="net.ifnames=0"
		syslinux-install_update -ami
		sed -i "s;\(^[[:space:]]*APPEND.*\)root=[^[:space:]]*;\1root=$root_dev${tmp:+ $tmp};" /boot/syslinux/syslinux.cfg
	fi

	if [ $needs_lvm2 -eq 1 ]; then
		mv /etc/lvm/lvm.conf.bak /etc/lvm/lvm.conf
		sed -i '/HOOKS/s/block/& lvm2/' /etc/mkinitcpio.conf
		mkinitcpio -p linux
	fi
}

configure_network() {
	local gateway dev ip

	dev=$(ls /sys/class/net | grep -v lo)
	if [ -n "$(ip -4 route show default | awk '{ print $3 }')" ]; then
		gateway=$(ip -4 route show default | awk '{ print $3 }')
		set -- $(ip addr show dev "$dev" | awk '($1 == "inet") { print $2 }')
	else
		gateway=$(ip -6 route show default | awk '{ print $3 }')
		set -- $(ip addr show dev "$dev" | awk '($1 == "inet6" && $2 !~ /^fe80/) { print $2 }')
	fi
	ip=$@

	# FIXME Not supported for "P2P" interfaces, such as venet, yet
	if [ "$network" = "systemd-networkd" ]; then
		cat > /etc/systemd/network/default.network <<-EOF
			[Match]
			Name=$dev

			[Network]
			Gateway=$gateway
		EOF
		for ip in $ip; do
			echo "Address=$ip"
		done >> /etc/systemd/network/default.network
		systemctl enable systemd-networkd
	elif [ "$network" = "netctl" ]; then
		cat > /etc/netctl/default <<-EOF
			Interface=$dev
			Connection=ethernet
			IP=static
			Address=($ip)
		EOF
		if [ "$gateway" = "0.0.0.0" ]; then
			echo 'Routes=(0.0.0.0/0)'
		else
			echo "Gateway=$gateway"
		fi >> /etc/netctl/default
		netctl enable default
	fi

	systemctl enable sshd
}

finalize() {
	# OpenVZ hacks
	if is_openvz; then
		local kernelver
		read -r _ _ kernelver _ < /proc/version
		if [ "$kernelver" '>' '3.10' ]; then
			# Virtuozzo 7 works with systemd, but it needs /etc/resolvconf/resolv.conf.d directory
			mkdir -p /etc/resolvconf/resolv.conf.d
		elif [ "$kernelver" '<' '2.6.32-042stab111.1' ]; then
			# Use my repository for OpenVZ-patched systemd
			sed -i 's;^#\[testing\]$;[tredaelli-systemd]\nServer = http://pkgbuild.com/~tredaelli/repo/systemd/$arch\n\n&;' /etc/pacman.conf
		fi
	fi

	# Enable SSH login for user root (#3)
	if [ -n "$ssh_key" ]; then
		mkdir -p /root/.ssh
		chmod 700 /root/.ssh
		echo "$ssh_key" > /root/.ssh/authorized_keys
		chmod 600 /root/.ssh/authorized_keys
	else
		sed -i '/^#PermitRootLogin\s/s/.*/&\nPermitRootLogin yes/' /etc/ssh/sshd_config
	fi
	if [ "$ssh_port" != "22" ]; then
		sed -i "s/^#\?Port [0-9]*/Port $ssh_port/" /etc/ssh/sshd_config
	fi
	sed -i 's/^#\(HostKey \/etc\/ssh\/ssh_host_ed25519_key\)/\1/' /etc/ssh/sshd_config

	# Configure timezone
	ln -sf "/usr/share/zoneinfo/$user_timezone" /etc/localtime

	# Configure systemd-timesyncd
	mkdir -p /etc/systemd/timesyncd.conf.d
	cat > /etc/systemd/timesyncd.conf.d/custom.conf <<-EOF
		[Time]
		NTP=time.google.com time.cloudflare.com
	EOF
	systemctl enable systemd-timesyncd

	# Configure systemd-resolved
	mkdir -p /etc/systemd/resolved.conf.d
	cat > /etc/systemd/resolved.conf.d/custom.conf <<-EOF
		[Resolve]
		DNS=$user_dns
	EOF
	systemctl enable systemd-resolved
	ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf

	# Configure hostname
	echo "$user_hostname" > /etc/hostname
	echo "127.0.1.1 $user_hostname.localdomain $user_hostname" >> /etc/hosts

	# Configure BBR
	case $enable_bbr in
	y|Y|yes|YES)
		cat > /etc/sysctl.d/99-bbr.conf <<-EOF
			net.core.default_qdisc = fq_pie
			net.ipv4.tcp_congestion_control = bbr
		EOF
		;;
	esac

	# Configure swap file
	if [ "$swap_size" -gt 0 ] 2>/dev/null; then
		swapoff /swapfile 2>/dev/null || true
		dd if=/dev/zero of=/swapfile bs=1M count=$((swap_size * 1024)) status=progress
		chmod 600 /swapfile
		mkswap /swapfile
		swapon /swapfile
		echo "/swapfile none swap defaults 0 0" >> /etc/fstab
	fi

	# Set mirrorlist
	: > /etc/pacman.d/mirrorlist
	for m in $(get_mirrors); do
		echo "Server = $m\$repo/os/\$arch" >> /etc/pacman.d/mirrorlist
	done

	cat <<-EOF
		Hi,
		your VM has successfully been reimaged with Arch Linux.

		This script configured $bootloader as bootloader and $network for networking.

		When you are finished with your post-installation, you'll need to reboot the VM the rough way:
		# sync ; reboot -f

		Then you'll be able to connect to your VM using SSH (port $ssh_port) and to login using your old root password (or "vps2arch" if you didn't have a root password).
	EOF
}

bootloader=grub
network=systemd-networkd
ssh_port=
ssh_key=
user_locale=
user_timezone=
user_dns=
user_hostname=
enable_bbr=
swap_size=
mirrors=

while getopts ":b:m:n:p:l:z:d:H:k:Bs:h" opt; do
	case $opt in
	b)
		if ! [ "$OPTARG" = "grub" -o "$OPTARG" = "syslinux" -o "$OPTARG" = "none" ]; then
			echo "Invalid bootloader specified" >&2
			exit 1
		fi
		bootloader="$OPTARG"
		;;
	m)
		mirrors="${mirrors:+$mirrors }$OPTARG"
		;;
	n)
		if ! [ "$OPTARG" = "systemd-networkd" -o "$OPTARG" = "netctl" -o "$OPTARG" = "none" ]; then
			echo "Invalid networking configuration system specified" >&2
			exit 1
		fi
		network="$OPTARG"
		;;
	p)
		ssh_port="$OPTARG"
		;;
	l)
		user_locale="$OPTARG"
		;;
	z)
		user_timezone="$OPTARG"
		;;
	d)
		user_dns="$OPTARG"
		;;
	H)
		user_hostname="$OPTARG"
		;;
	k)
		ssh_key="$OPTARG"
		;;
	B)
		enable_bbr=y
		;;
	s)
		swap_size="$OPTARG"
		;;
	h)
		cat <<-EOF
			usage: ${0##*/} [options]

			  Options:
			    -b (grub|syslinux)           Use the specified bootloader. When this option is omitted, it defaults to grub.
			    -n (systemd-networkd|netctl) Use the specified networking configuration system. When this option is omitted, it defaults to systemd-networkd.
			    -m mirror                    Use the provided mirror (you can specify this option more than once).
			    -p port                      Use the specified SSH port.
			    -l locale                    Use the specified locale.
			    -z timezone                  Use the specified timezone.
			    -d "dns1 dns2"               Use the specified DNS servers (space separated).
			    -H hostname                  Use the specified hostname.
			    -k "ssh-key"                 Use the specified public key for root login.
			    -B                           Enable BBR.
			    -s size                      Create a swap file of the specified size (in GiB).

			    -h                           Print this help message

			    Warning:
			      On OpenVZ containers the bootloader will be not installed and the networking configuration system will be enforced to netctl.
		EOF
		exit 0
		;;
	:)
		printf "%s: option requires an argument -- '%s'\n" "${0##*/}" "$OPTARG" >&2
		exit 1
		;;
	?)
		printf "%s: invalid option -- '%s'\n" "${0##*/}" "$OPTARG" >&2
		exit 1
		;;
	esac
done
shift $((OPTIND - 1))

if [ -z "$ssh_port" ]; then
	printf "Enter SSH port [22]: "
	read -r ssh_port
	ssh_port=${ssh_port:-22}
fi

if [ -z "$user_locale" ]; then
	printf "Enter locale [en_US.UTF-8]: "
	read -r user_locale
	user_locale=${user_locale:-en_US.UTF-8}
fi

if [ -z "$user_timezone" ]; then
	printf "Enter timezone [UTC]: "
	read -r user_timezone
	user_timezone=${user_timezone:-UTC}
fi

if [ -z "$user_dns" ]; then
	printf "Enter DNS servers [1.1.1.1]: "
	read -r user_dns
	user_dns=${user_dns:-1.1.1.1}
fi

if [ -z "$user_hostname" ]; then
	printf "Enter hostname [archlinux]: "
	read -r user_hostname
	user_hostname=${user_hostname:-archlinux}
fi

if [ -z "$ssh_key" ]; then
	printf "Do you want to use key-based login? [y/N]: "
	read -r use_key
	case "$use_key" in
	[yY][eE][sS]|[yY])
		printf "Enter public key: "
		read -r ssh_key
		;;
	*)
		ssh_key=""
		;;
	esac
fi

if [ -z "$enable_bbr" ]; then
	printf "Enable BBR? [y/N]: "
	read -r enable_bbr
fi

if [ -z "$swap_size" ]; then
	# Check if there are any swap partitions. Swap files are ignored because
	# they will be deleted during the reinstallation process.
	if [ "$(swapon --show=TYPE --noheadings | grep -c "partition")" -eq 0 ]; then
		[ "$(swapon --show --noheadings | wc -l)" -gt 0 ] && printf "Only file-based swap detected (will be deleted).\n"
		printf "No swap partition detected. Do you want to add a swap file? [y/N]: "
		read -r add_swap
		case "$add_swap" in
		[yY][eE][sS]|[yY])
			printf "Enter swap file size in GiB [1]: "
			read -r swap_size
			swap_size=${swap_size:-1}
			;;
		*)
			swap_size=0
			;;
		esac
	else
		swap_size=0
	fi
fi

[ -z "$mirrors" ] && mirrors=$(get_mirrors)


if is_openvz; then
	bootloader=none
	network=netctl
elif is_lxc; then
	bootloader=none
fi

cd /
download_and_extract_bootstrap
configure_chroot
save_root_pass
swapoff -a 2>/dev/null || true
delete_all
install_packages
restore_root_pass
cleanup
configure_bootloader
configure_network
finalize
